# Generated by Django 2.1 on 2020-07-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('join_year', models.IntegerField(blank=True)),
                ('last_year', models.IntegerField(blank=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Designation')),
            ],
        ),
    ]
